---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshach-configuredservice
  namespace: sym-admin
spec:
  selector:
    matchLabels:
      name: meshach-configuredservice
  replicas: 1
  template:
    metadata:
      labels:
        name: meshach-configuredservice
    spec:
      containers:
        - name: meshach-configuredservice
          image: controller:latest
          imagePullPolicy: Always
          args:
            - "ctl"
            - "-v"
            - "4"
            - "--enable-configuredservice"
            - "--leader-enable=false"
            - "--watch-istio-crd=true"
            # - "--leader-election-id"
            - "--qps=180.0"
            - "--burst=200"
            # - "meshach-lock-configuredservice"
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 1
              memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshach-serviceconfig
  namespace: sym-admin
spec:
  selector:
    matchLabels:
      name: meshach-serviceconfig
  replicas: 1
  template:
    metadata:
      labels:
        name: meshach-serviceconfig
    spec:
      containers:
        - name: meshach-serviceconfig
          image: controller:latest
          imagePullPolicy: Always
          args:
            - "ctl"
            - "-v"
            - "4"
            - "--enable-serviceconfig"
            - "--leader-enable=false"
            - "--qps=80.0"
            - "--burst=100"
            # - "--leader-election-id"
            # - "meshach-lock-serviceconfig"
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 1
              memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshach-meshconfig
  namespace: sym-admin
spec:
  selector:
    matchLabels:
      name: meshach-meshconfig
  replicas: 1
  template:
    metadata:
      labels:
        name: meshach-meshconfig
    spec:
      containers:
        - name: meshach-meshconfig
          image: controller:latest
          imagePullPolicy: Always
          args:
            - "ctl"
            - "-v"
            - "4"
            - "--enable-meshconfig"
            - "--leader-enable=false"
            - "--qps=80.0"
            - "--burst=100"
            # - "--leader-election-id"
            # - "meshach-lock-meshconfig"
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 1
              memory: 256Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: meshach-serviceaccessor
  namespace: sym-admin
spec:
  selector:
    matchLabels:
      name: meshach-serviceaccessor
  replicas: 1
  template:
    metadata:
      labels:
        name: meshach-serviceaccessor
    spec:
      containers:
        - name: meshach-serviceaccessor
          image: controller:latest
          imagePullPolicy: Always
          args:
            - "ctl"
            - "-v"
            - "4"
            - "--enable-serviceaccessor"
            - "--leader-enable=false"
            - "--qps=80.0"
            - "--burst=100"
            # - "--leader-election-id"
            # - "meshach-lock-serviceaccessor"
          resources:
            limits:
              cpu: 2
              memory: 512Mi
            requests:
              cpu: 1
              memory: 256Mi
